version: "3.9"

services:
  db:
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    image: postgres:14.1
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}

  app:
    environment:
      - DJANGO_PORT
      - DJANGO_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - DEBUG
      - SECRET_KEY
      - DJANGO_MODE
    image: ${APP_DOCKER_TAG}
    build:
      context: ..
      dockerfile: ./docker/django.Dockerfile
      args:
        APP_HOME: ${APP_HOME}
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db
